#logLevel
logging:
  level:
    org : info
    com : debug
    root : info

#mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coin?characterEncoding=UTF-8&serverTimezone=UTC
    username: coin
    password: coin123
    driver-class-name: com.mysql.cj.jdbc.Driver

#port
server:
  port: 8081

#mybaits
mybatis:
  mapper-locations: static/mapper/*.xml